site_name: pipen-filters
repo_url: https://github.com/pwwang/pipen-filters
repo_name: pwwang/pipen-filters
theme:
    name: 'rtd'
    logo: 'pipen-filters.png'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi:
        src_dirs: ['pipen_filters']
extra_css:
    - style.css
nav:
    - 'API': mkapi/api/pipen_filters
