name: Docs

on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install -v --with=docs
      - name: Build docs
        run: mkdocs build
        if : success()
      - name: Deploy docs
        run: |
          mkdocs gh-deploy --clean --force
        # if: success() && github.ref == 'refs/heads/master'
